### ISSUE TITLE
Abuse.ch Ransomware lookup can block processing

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-threatintel#18]
A timeout in the table refresh can apparently hold up processing even through this should be completely async.

```
2016-12-07T16:23:13.997-06:00 ERROR [LocalCopyListProvider] Could not refresh [Abuse.ch Ransomware tracker] source table.
java.util.concurrent.ExecutionException: Could not refresh local source table.
	at org.graylog.plugins.threatintel.providers.abusech.AbuseChRansomLookupProvider.refreshTable(AbuseChRansomLookupProvider.java:113) ~[graylog-plugin-threatintel-0.9.0.jar:?]
	at org.graylog.plugins.threatintel.providers.LocalCopyListProvider.initialize(LocalCopyListProvider.java:114) [graylog-plugin-threatintel-0.9.0.jar:?]
	at org.graylog.plugins.threatintel.providers.abusech.domain.AbuseChRansomDomainLookupFunction.<init>(AbuseChRansomDomainLookupFunction.java:31) [graylog-plugin-threatintel-0.9.0.jar:?]
	at org.graylog.plugins.threatintel.providers.abusech.domain.AbuseChRansomDomainLookupFunction$$FastClassByGuice$$b2698faf.newInstance(<generated>) [graylog-plugin-threatintel-0.9.0.jar:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) [graylog.jar:?]

```

**Comment by lennartkoopmann** [comment]
Confirmed that this is not an issue and timeouts are working as expected.
